#!/usr/bin/env bash
#
# 把模板里的占位扩展名（默认 `my_extension`）换成你的扩展名 —— 克隆模板后的第一件事。
#
# 它改的是「扩展名」这一个字符串：Cargo.toml（crate 名与 [[example]] 名）、Makefile 的 EXTENSION_NAME、
# src/extension/mod.rs 的 duckfn_entrypoint!、Justfile 的 extension_name、CI 工作流的 extension_name，
# 以及 README / DEVELOPMENT 里出现的那些（加载路径、示例命令）。这些地方必须处处一致，漏一处就是
# `LOAD` 失败或 CI 构建出的产物名字对不上。
#
# 它**不**改示例函数的名字（`my_greet` / `my_greet_checked` / `my_sum`）：那些是给你替换的域代码，
# 不是扩展名的一部分。函数名前缀的约定见 AGENTS.md，换完自己顺手改掉（连同 test/sql 里的用例）。
#
# 用法 / Usage：
#   bash scripts/rename.sh <new-extension-name> [old-extension-name]
#
# 例 / Example：
#   just rename csv_stats                        # 第一次改名，旧名默认 my_extension
#   bash scripts/rename.sh csv_stats              # 同上
#   bash scripts/rename.sh csv_stats my_extension # 第二次改名时把旧名字显式给出
#
# A one-shot rename of the placeholder extension name (`my_extension` by default) — the first thing to
# do after cloning this template. It touches the extension name and nothing else: the sample functions
# are domain code for you to replace, and their prefix convention lives in AGENTS.md.
set -euo pipefail

die() {
    echo "error: $*" >&2
    exit 1
}

NEW=${1:-}
OLD=${2:-my_extension}

[ -n "$NEW" ] || die "用法 / usage: bash scripts/rename.sh <new-extension-name> [old-extension-name]"

# 扩展名规则（DuckDB 侧真正的要求）：全小写、只含下划线与数字，不能以数字开头。
# 它与产物文件名、入口点符号都绑在一起，所以这里先挡住明显不合法的写法。
#
# The rule DuckDB actually imposes: all lowercase, underscores and digits only, not starting with a
# digit. The name is tied to the artifact file name and the entry-point symbol, so reject bad spellings
# here rather than after a build.
case "$NEW" in
    [a-z]*)
        printf '%s' "$NEW" | grep -qE '^[a-z0-9_]+$' || die "扩展名只能用小写字母、数字与下划线 / only [a-z0-9_]"
        ;;
    *)
        die "扩展名必须以小写字母开头 / must start with a lowercase letter"
        ;;
esac

[ "$NEW" != "$OLD" ] || die "新名字与旧名字相同 / new name equals old name"

git rev-parse --is-inside-work-tree >/dev/null 2>&1 || die "不在 git 仓库里 / not inside a git repository"

# 两种写法一起换：扩展名（下划线）与常见的仓库名（连字符）。
#
# Both spellings are rewritten: the extension name (underscores) and the usual repository name
# (hyphens).
OLD_DASH=${OLD//_/-}
NEW_DASH=${NEW//_/-}

# 候选文件：仓库里所有**未被忽略**的文件（含尚未 git add 的新文件），排除两份不该动的：
#   - Cargo.lock：由下面的 cargo 命令按新名字重写，sed 改它反而容易改坏 checksum 之外的字段；
#   - 这个脚本自己：它默认的旧名字要在下一次改名时仍然可用。
#
# Candidates: every file in the repository that is not git-ignored (untracked ones included), minus two
# that must not be rewritten — Cargo.lock (regenerated by the cargo command below) and this script
# itself (its default old name has to survive for the next rename).
mapfile -t files < <(git grep --untracked -l -F -e "$OLD" -e "$OLD_DASH" -- . \
    ':(exclude)Cargo.lock' ':(exclude)scripts/rename.sh')

if [ "${#files[@]}" -eq 0 ]; then
    echo "没有文件包含 '${OLD}'，什么都没改 / no file mentions '${OLD}', nothing to do"
    exit 0
fi

echo "扩展名 / extension name: ${OLD} -> ${NEW}"
for f in "${files[@]}"; do
    # 旧名字里只有小写字母、数字、下划线与连字符，没有任何 sed 正则元字符，直接当模式用。
    #
    # The old name holds only lowercase letters, digits, underscores and hyphens — no sed
    # metacharacters — so it can be used as a pattern as it is.
    sed -i "s/${OLD}/${NEW}/g; s/${OLD_DASH}/${NEW_DASH}/g" "$f"
    echo "  updated $f"
done

# 冒烟测试的文件名也带扩展名（`test/sql/<扩展名>.test`），文件名不归 sed 管，单独搬一下。
#
# The smoke test is named after the extension too (`test/sql/<name>.test`); sed cannot move files, so
# that one is renamed separately.
if [ -f "test/sql/${OLD}.test" ]; then
    if git ls-files --error-unmatch "test/sql/${OLD}.test" >/dev/null 2>&1; then
        git mv "test/sql/${OLD}.test" "test/sql/${NEW}.test"
    else
        mv "test/sql/${OLD}.test" "test/sql/${NEW}.test"
    fi
    echo "  renamed test/sql/${OLD}.test -> test/sql/${NEW}.test"
fi

# Cargo.lock 里写着旧包名，让 cargo 自己按新名字重写这一条（依赖的版本不动）。
#
# Cargo.lock still names the old package; let cargo rewrite that one entry under the new name
# (dependency versions are left alone).
cargo metadata --format-version 1 >/dev/null

echo
echo "已改名的文件如上（共 ${#files[@]} 个）。还要手工过一遍："
echo "  1. 示例函数（my_greet / my_greet_checked / my_sum）与 test/sql/*.test —— 换成你自己的 API，"
echo "     顺手把 AGENTS.md 里函数名前缀那条约定（默认 my_）改成你的前缀"
echo "  2. docs/docusaurus.config.ts 的 REPO_URL —— 改成你的仓库地址（本脚本只改扩展名，不动 URL；"
echo "     它同时是首页徽章与可运行 SQL 预加载的来源，不换会去模板仓库找 Release）"
echo "  3. community-extension/description.yml —— extension.name / description / maintainers / repo"
echo "  4. AGENTS.md 的 {{PROJECT_GOAL}} 占位符"
echo "  5. README / DEVELOPMENT 的说明文字（模板的来历、示例用法）"
echo "  6. LICENSE 的版权人、Cargo.toml 的 duckfn 版本"
echo
git --no-pager diff --stat
