import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * 两个侧边栏，对应顶栏两项（见 docusaurus.config.ts 的 navbar）：
 *
 * - `userGuide` —— 怎么写这个扩展：`intro` 加 `getting-started/`、`guide/` 两个目录。
 * - `development` —— 怎么构建、测试与发布它：`build-and-release` 与 `community-extension`。
 *
 * 页面不搬家，URL 因此不变。目录内部的顺序仍由各页的 `sidebar_position` 决定；上面两个分类之所以
 * 手写出来，是因为 `autogenerated` 条目生成的是**目录的内容**、而不是目录本身。
 *
 * Two sidebars, one per navbar entry (see the navbar in docusaurus.config.ts):
 *
 * - `userGuide` — writing the extension: `intro` plus the `getting-started/` and `guide/` folders.
 * - `development` — building, testing and releasing it: `build-and-release` and `community-extension`.
 *
 * Pages keep the folder they are in, so their URLs stay stable. Inside a folder the order still comes
 * from `sidebar_position`; the two categories below are spelled out because an `autogenerated` entry
 * yields a folder's *contents*, not the folder itself.
 */
const sidebars: SidebarsConfig = {
  userGuide: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      link: {
        type: 'generated-index',
        description: 'Rename the template, build it, load it, and see where everything lives.',
      },
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Guide',
      link: {
        type: 'generated-index',
        description: 'The sample functions line by line, and how to test your own.',
      },
      items: [{type: 'autogenerated', dirName: 'guide'}],
    },
  ],
  development: ['build-and-release', 'community-extension'],
};

export default sidebars;