import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * 两个侧边栏，对应顶栏两项（见 docusaurus.config.ts 的 navbar）：
 *
 * - `userGuide` —— 面向插件使用者：简介、安装加载、函数参考。
 * - `development` —— 面向开发者：项目结构、写函数、测试、构建发版、社区扩展注册。
 *
 * 页面按物理路径引用，不再用 autogenerated（因为同一目录下的文件分属不同侧边栏）。
 *
 * Two sidebars, one per navbar entry (see the navbar in docusaurus.config.ts):
 *
 * - `userGuide` — for extension users: introduction, install & load, function reference.
 * - `development` — for contributors: project structure, writing functions, testing, build & release,
 *   community-extension registration.
 *
 * Pages are referenced by their explicit IDs (files in the same folder now belong to different
 * sidebars, so autogenerated is no longer suitable).
 */
const sidebars: SidebarsConfig = {
  userGuide: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      link: {
        type: 'generated-index',
        description: 'Install the extension and run your first statistical queries.',
      },
      items: ['getting-started/quick-start'],
    },
    {
      type: 'category',
      label: 'Guide',
      link: {
        type: 'generated-index',
        description: 'Browse all 252 functions organized by category.',
      },
      items: ['guide/functions'],
    },
  ],
  development: [
    'getting-started/project-structure',
    'guide/writing-functions',
    'guide/testing',
    'build-and-release',
    'community-extension',
  ],
};

export default sidebars;