// ============================================================================
// statrs::statistics 的聚合版包装：一列进、一个值出
//
// 为什么是聚合而不是「LIST + 标量」：`SELECT sr_mean(x) FROM t GROUP BY g` 是数据库用户
// 写统计查询的默认形状，换成标量就得先 `list(x)` 再喂给函数，SQL 更长、也更绕。
//
// NULL 语义（与 statrs 对齐、向 SQL 用户侧传播）：
//   - SQL NULL 行不进状态（聚合惯例，与 DuckDB 自带的 mean/stddev 一致）；
//   - statrs 算不出的（空组、方差类不足 2 个值、quantile 的 tau 越界…）返回 NAN，
//     统一经 `nan_to_null` 折成 SQL NULL —— NAN 不会作为值出现在结果里；
//   - 整组没有一行有效数据时，结果同样是 NULL（空 slice 上 statrs 一律给 NAN）。
//
// 结构：`auto_collect = true` 把「收集整列 + 换最后一跳算式」的样板（状态结构体、
// `DuckAggregateState`、逐行 push 的行处理器）全部收进宏里 —— 被标注函数直接就是
// finalize：`Vec<f64>` 参数是要收集的列，返回值是聚合结果。宏生成的状态与过去手写的
// `SummaryState<S>` 等价（每列一个 `Vec<T>`，`simple_combine` 拼接、`result` 求值），
// 并行 combine 与 NULL 跳过的语义原样不变。
// 具体算哪个统计量仍由类型参数 `S` 在 finalize 里静态派发（marker struct + `Summary`
// trait）—— 不用宏：宏生成的代码块类型不安全、IDE 也不补全，而每个算式只是
// `Summary` 实现里委托 statrs 的一行。
//
// 状态先收齐整列数据、finalize 时把切片交给 statrs 计算：语义与「在本机直接调 statrs」
// 严格一致是第一优先级，median/quantile 这类顺序统计量本来也需要全量数据（DuckDB 自带的
// quantile 同样在状态里攒数据）。
//
// Wrapping statrs::statistics as aggregates: a column in, one value out.
//
// Structure: `auto_collect = true` absorbs the collect-then-compute boilerplate (state struct,
// `DuckAggregateState`, the one-line row handler) into the macro — the annotated function *is* the
// finalize handler: a `Vec<f64>` parameter is the collected column, the return value is the result.
// The generated state is exactly the former hand-written `SummaryState<S>` (a `Vec<T>` per column,
// merged in `simple_combine`, evaluated in `result`), so parallel combine and NULL-skipping
// semantics are unchanged. The concrete statistic is still dispatched by the type parameter `S`
// inside finalize (marker structs + the `Summary` trait) — no macro: generated code is type-unsafe
// and invisible to the IDE, and each statistic is just the one-line statrs delegation in its
// `Summary` impl.
//
// NULL semantics as before: SQL NULL rows never enter the state; whatever statrs spells NAN
// (empty group, fewer than two samples, out-of-range tau, negatives in the geometric/harmonic
// means) becomes SQL NULL through the shared `nan_to_null`.
// ============================================================================

use duckfn::{DuckFirst, DuckOptionResult, duck_aggregate_function};
use statrs::statistics::{Data, OrderStatistics, Statistics};

/// 「一列切片算一个汇总统计量」的静态派发点。实现体只有委托给 statrs 的一行。
///
/// The static dispatch point for "compute one summary statistic over a column". Each body is the
/// one-line delegation to statrs.
trait Summary {
    fn eval(values: &[f64]) -> f64;
}

// marker 类型本身不带任何逻辑，存在的意义就是让 `summarize::<ArithmeticMean>` 与
// `summarize::<Median>` 成为两条可分别派发的算式。
#[derive(Default, Debug, Clone, Copy)] struct ArithmeticMean;
#[derive(Default, Debug, Clone, Copy)] struct GeometricMean;
#[derive(Default, Debug, Clone, Copy)] struct HarmonicMean;
#[derive(Default, Debug, Clone, Copy)] struct QuadraticMean;
#[derive(Default, Debug, Clone, Copy)] struct Median;
#[derive(Default, Debug, Clone, Copy)] struct SampleVariance;
#[derive(Default, Debug, Clone, Copy)] struct SampleStdDev;
#[derive(Default, Debug, Clone, Copy)] struct PopulationVariance;
#[derive(Default, Debug, Clone, Copy)] struct PopulationStdDev;

// 集中趋势：均值族对切片直接算（`Statistics` 落在所有 `IntoIterator<Item = Borrow<f64>>`
// 上，`&[f64]` 即是）；中位数走 `OrderStatistics`，它按 `&mut` 就地选择，finalize 时给一份
// 可重排的拷贝 —— 状态里收集的原始列不动。
impl Summary for ArithmeticMean {
    fn eval(values: &[f64]) -> f64 {
        values.mean()
    }
}

impl Summary for GeometricMean {
    fn eval(values: &[f64]) -> f64 {
        values.geometric_mean()
    }
}

impl Summary for HarmonicMean {
    fn eval(values: &[f64]) -> f64 {
        values.harmonic_mean()
    }
}

impl Summary for QuadraticMean {
    fn eval(values: &[f64]) -> f64 {
        values.quadratic_mean()
    }
}

impl Summary for Median {
    fn eval(values: &[f64]) -> f64 {
        let mut data = Data::new(values.to_vec());
        data.median()
    }
}

// 离散程度：样本版（Bessel 修正、除以 N-1）与总体版（除以 N）。空组与样本不足在 statrs 里
// 都是 NAN，落到 SQL 侧就是 NULL —— 与 DuckDB 自带 var/stddev 对单行输入给 NULL 一致。
impl Summary for SampleVariance {
    fn eval(values: &[f64]) -> f64 {
        values.variance()
    }
}

impl Summary for SampleStdDev {
    fn eval(values: &[f64]) -> f64 {
        values.std_dev()
    }
}

impl Summary for PopulationVariance {
    fn eval(values: &[f64]) -> f64 {
        values.population_variance()
    }
}

impl Summary for PopulationStdDev {
    fn eval(values: &[f64]) -> f64 {
        values.population_std_dev()
    }
}

/// 全部汇总统计量共用的 finalize：收到的 `Vec<f64>` 就是收集好的整列，按类型参数派发。
///（状态由 `auto_collect` 在宏里生成，这里只剩算式本身。）
///
/// The finalize shared by every summary aggregate: the `Vec<f64>` is the collected column, dispatched
/// on the type parameter. (The state itself is generated by `auto_collect` inside the macro.)
fn summarize<S: Summary>(values: Vec<f64>) -> DuckOptionResult<f64> {
    super::nan_to_null(S::eval(&values))
}

/// `sr_mean(x)`：算术平均（`Statistics::mean`）。
///
/// ```sql
/// SELECT sr_mean(x) FROM (VALUES (1.0), (2.0), (3.0)) t(x);  -- 2.0
/// SELECT sr_mean(x) FROM range(0) t(x);                      -- NULL（空组）
/// ```
#[duck_aggregate_function(
    auto_collect = true,
    description = "Arithmetic mean of a DOUBLE column, NULL when no row is non-NULL",
    comment = "SQL NULL rows are skipped; statrs' NAN for an empty group becomes SQL NULL",
    example = "SELECT sr_mean(x) FROM (VALUES (1.0), (2.0), (3.0)) t(x)"
)]
fn sr_mean(input: Vec<f64>) -> DuckOptionResult<f64> {
    summarize::<ArithmeticMean>(input)
}

/// `sr_geometric_mean(x)`：几何平均（`Statistics::geometric_mean`），含负数 NULL、含 0 出 0。
///
/// ```sql
/// SELECT sr_geometric_mean(x) FROM (VALUES (1.0), (2.0), (3.0)) t(x);  -- 1.8171205928321397
/// SELECT sr_geometric_mean(x) FROM (VALUES (-1.0), (2.0)) t(x);        -- NULL
/// ```
#[duck_aggregate_function(
    auto_collect = true,
    description = "Geometric mean of a DOUBLE column, NULL when a value is negative or no row is non-NULL",
    comment = "A negative value makes the statistic undefined, which comes back as NULL",
    example = "SELECT sr_geometric_mean(x) FROM (VALUES (1.0), (2.0), (3.0)) t(x)"
)]
fn sr_geometric_mean(input: Vec<f64>) -> DuckOptionResult<f64> {
    summarize::<GeometricMean>(input)
}

/// `sr_harmonic_mean(x)`：调和平均（`Statistics::harmonic_mean`）。
///
/// ```sql
/// SELECT sr_harmonic_mean(x) FROM (VALUES (1.0), (2.0), (3.0)) t(x);  -- 1.6363636363636365
/// ```
#[duck_aggregate_function(
    auto_collect = true,
    description = "Harmonic mean of a DOUBLE column, NULL when a value is negative or no row is non-NULL",
    comment = "A negative value makes the statistic undefined, which comes back as NULL",
    example = "SELECT sr_harmonic_mean(x) FROM (VALUES (1.0), (2.0), (3.0)) t(x)"
)]
fn sr_harmonic_mean(input: Vec<f64>) -> DuckOptionResult<f64> {
    summarize::<HarmonicMean>(input)
}

/// `sr_quadratic_mean(x)`：平方均值 / RMS（`Statistics::quadratic_mean`）。
///
/// ```sql
/// SELECT sr_quadratic_mean(x) FROM (VALUES (0.0), (3.0), (-2.0)) t(x);  -- 2.0816659994661326
/// ```
#[duck_aggregate_function(
    auto_collect = true,
    description = "Quadratic mean (root mean square) of a DOUBLE column, NULL when no row is non-NULL",
    comment = "SQL NULL rows are skipped; statrs' NAN for an empty group becomes SQL NULL",
    example = "SELECT sr_quadratic_mean(x) FROM (VALUES (1.0), (2.0), (3.0)) t(x)"
)]
fn sr_quadratic_mean(input: Vec<f64>) -> DuckOptionResult<f64> {
    summarize::<QuadraticMean>(input)
}

/// `sr_median(x)`：中位数（`OrderStatistics::median`，就地选择算法），偶数个取中间两数平均。
///
/// ```sql
/// SELECT sr_median(x) FROM (VALUES (-1.0), (5.0), (0.0), (-3.0), (10.0), (-0.5), (4.0), (1.0), (6.0)) t(x);  -- 1.0
/// SELECT sr_median(x) FROM (VALUES (1.0), (2.0), (3.0), (4.0)) t(x);  -- 2.5
/// ```
#[duck_aggregate_function(
    auto_collect = true,
    description = "Median of a DOUBLE column, NULL when no row is non-NULL",
    comment = "Even-length inputs average the two middle values, statrs' own convention",
    example = "SELECT sr_median(x) FROM (VALUES (3.0), (1.0), (2.0)) t(x)"
)]
fn sr_median(input: Vec<f64>) -> DuckOptionResult<f64> {
    summarize::<Median>(input)
}

/// `sr_variance(x)`：样本方差（`Statistics::variance`，Bessel 修正、除以 N-1）。
///
/// ```sql
/// SELECT sr_variance(x) FROM (VALUES (0.0), (3.0), (-2.0)) t(x);  -- 19/3
/// SELECT sr_variance(x) FROM (VALUES (1.0)) t(x);                 -- NULL
/// ```
#[duck_aggregate_function(
    auto_collect = true,
    description = "Sample variance of a DOUBLE column (Bessel-corrected), NULL when fewer than two rows are non-NULL",
    comment = "One value has no sample variance; the result is NULL, not 0",
    example = "SELECT sr_variance(x) FROM (VALUES (0.0), (3.0), (-2.0)) t(x)"
)]
fn sr_variance(input: Vec<f64>) -> DuckOptionResult<f64> {
    summarize::<SampleVariance>(input)
}

/// `sr_std_dev(x)`：样本标准差。
///
/// ```sql
/// SELECT sr_std_dev(x) FROM (VALUES (0.0), (3.0), (-2.0)) t(x);  -- sqrt(19/3)
/// ```
#[duck_aggregate_function(
    auto_collect = true,
    description = "Sample standard deviation of a DOUBLE column (Bessel-corrected), NULL when fewer than two rows are non-NULL",
    comment = "One value has no sample standard deviation; the result is NULL, not 0",
    example = "SELECT sr_std_dev(x) FROM (VALUES (0.0), (3.0), (-2.0)) t(x)"
)]
fn sr_std_dev(input: Vec<f64>) -> DuckOptionResult<f64> {
    summarize::<SampleStdDev>(input)
}

/// `sr_population_variance(x)`：总体方差（除以 N）。
///
/// ```sql
/// SELECT sr_population_variance(x) FROM (VALUES (0.0), (3.0), (-2.0)) t(x);  -- 38/9
/// ```
#[duck_aggregate_function(
    auto_collect = true,
    description = "Population variance of a DOUBLE column, NULL when no row is non-NULL",
    comment = "Single-row groups yield a real number here (dividing by N), unlike the sample family",
    example = "SELECT sr_population_variance(x) FROM (VALUES (0.0), (3.0), (-2.0)) t(x)"
)]
fn sr_population_variance(input: Vec<f64>) -> DuckOptionResult<f64> {
    summarize::<PopulationVariance>(input)
}

/// `sr_population_std_dev(x)`：总体标准差（除以 N）。
///
/// ```sql
/// SELECT sr_population_std_dev(x) FROM (VALUES (0.0), (3.0), (-2.0)) t(x);  -- sqrt(38/9)
/// ```
#[duck_aggregate_function(
    auto_collect = true,
    description = "Population standard deviation of a DOUBLE column, NULL when no row is non-NULL",
    comment = "Single-row groups yield a real number here (dividing by N), unlike the sample family",
    example = "SELECT sr_population_std_dev(x) FROM (VALUES (0.0), (3.0), (-2.0)) t(x)"
)]
fn sr_population_std_dev(input: Vec<f64>) -> DuckOptionResult<f64> {
    summarize::<PopulationStdDev>(input)
}

/// `sr_quantile(x, tau)`：tau 分位数（`OrderStatistics::quantile`）。第二个参数按常量写
/// （聚合参数是逐行的列，`0.975` 这样的字面量每行都是同一个值），用 `DuckFirst<f64>` 声明
/// —— 它逐行不变，宏只解析一次，进 finalize 的就是一个 `f64`。tau 为 NULL 的行整行不进
/// 收集，与「NULL 输入不进函数体」的标量规则同源；空组（或全 NULL）时 `DuckFirst` 无从解析，
/// `auto_collect` 直接报 NULL，函数不会被调用 —— 与原手写的 `QuantileState` 语义一致。
///
/// ```sql
/// SELECT sr_quantile(x, 0.5) FROM (VALUES (1.0), (2.0), (3.0), (4.0)) t(x);  -- 2.5
/// SELECT sr_quantile(x, 1.5) FROM (VALUES (1.0), (2.0)) t(x);                -- NULL（tau 越界）
/// ```
#[duck_aggregate_function(
    auto_collect = true,
    description = "Tau quantile of a DOUBLE column, tau as the second (constant) argument, NULL when empty or tau is not in [0, 1]",
    comment = "Write the tau argument as a literal; a NULL tau skips the row entirely, like any NULL input",
    example = "SELECT sr_quantile(x, 0.5) FROM (VALUES (1.0), (2.0), (3.0), (4.0)) t(x)"
)]
fn sr_quantile(input: Vec<f64>, tau: DuckFirst<f64>) -> DuckOptionResult<f64> {
    let mut data = Data::new(input);
    super::nan_to_null(data.quantile(tau))
}
