// ============================================================================
// 协方差聚合：两列成对进、一个值出
//
// 两列参数按行配对：任何一列是 NULL 的行整行不进状态（聚合的 NULL 跳过规则），所以
// 「两条边长度不等」在这个形态下根本构造不出来 —— LIST + 标量的形态才需要手工检查
// 长度并报错（statrs 对不等长是直接 panic 的）。
//
// 形状与 aggregate_summary.rs 相同：`auto_collect = true` 把「按行配对收集 + finalize 算一次」
// 的样板收进宏里，被标注函数直接就是 finalize（两个 `Vec<f64>` 参数就是配对收集好的两列）；
// 具体算样本还是总体协方差仍由 `Pairwise` 的实现（marker struct + 小 trait）在编译期静态派发，
// 不用宏。NULL 跳过与并行 combine 的语义与原手写状态完全一致。
//
// NULL 语义同样对齐 statrs：配对后不足 2 行返回 NAN，统一折成 SQL NULL。
//
// Covariance aggregates: two columns in, paired row by row.
//
// A NULL in either column skips the whole row, so the "unequal-length" case that statrs panics on
// is unconstructible in this shape — the row pairing itself takes care of it.
//
// Same shape as aggregate_summary.rs: `auto_collect = true` absorbs the paired-collect-then-compute
// boilerplate into the macro, and the annotated function *is* the finalize handler (two `Vec<f64>`
// parameters are the paired columns). The concrete statistic is still dispatched statically by the
// `Pairwise` impls (marker structs + a small trait). No macro.
// ============================================================================

use duckfn::{DuckOptionResult, duck_aggregate_function};
use statrs::statistics::Statistics;

/// 「两条配对切片算一个统计量」的静态派发点。
///
/// The static dispatch point for "compute one statistic over two paired columns".
trait Pairwise {
    fn eval(xs: &[f64], ys: &[f64]) -> f64;
}

#[derive(Default, Debug, Clone, Copy)] struct SampleCovariance;
#[derive(Default, Debug, Clone, Copy)] struct PopulationCovariance;

// 样本版带 Bessel 修正（除以 N-1），总体版除以 N；与单列的方差族一一对应。
impl Pairwise for SampleCovariance {
    fn eval(xs: &[f64], ys: &[f64]) -> f64 {
        xs.covariance(ys)
    }
}

impl Pairwise for PopulationCovariance {
    fn eval(xs: &[f64], ys: &[f64]) -> f64 {
        xs.population_covariance(ys)
    }
}

/// 两条配对列共用的 finalize：拿到的两个 `Vec<f64>` 就是按行配对收集好的列，
/// 按 `P` 派发。（状态由 `auto_collect` 在宏里生成，这里只剩算式本身。）
///
/// The finalize shared by the paired aggregates: the two `Vec<f64>`s are the columns collected in
/// pairs, dispatched on `P`. (The state itself is generated by `auto_collect` inside the macro.)
fn pairwise<P: Pairwise>(xs: Vec<f64>, ys: Vec<f64>) -> DuckOptionResult<f64> {
    super::nan_to_null(P::eval(&xs, &ys))
}

/// `sr_covariance(x, y)`：样本协方差（`Statistics::covariance`，Bessel 修正）。
///
/// ```sql
/// SELECT sr_covariance(x, y) FROM (VALUES (0.0, -5.0), (3.0, 4.0), (-2.0, 10.0)) t(x, y);  -- -5.5
/// ```
#[duck_aggregate_function(
    auto_collect = true,
    description = "Sample covariance of two DOUBLE columns (Bessel-corrected), NULL when fewer than two rows are fully non-NULL",
    comment = "A row with a NULL in either column is skipped entirely, keeping the two columns paired",
    example = "SELECT sr_covariance(x, y) FROM (VALUES (0.0, -5.0), (3.0, 4.0), (-2.0, 10.0)) t(x, y)"
)]
fn sr_covariance(x: Vec<f64>, y: Vec<f64>) -> DuckOptionResult<f64> {
    pairwise::<SampleCovariance>(x, y)
}

/// `sr_population_covariance(x, y)`：总体协方差（除以 N）。
///
/// ```sql
/// SELECT sr_population_covariance(x, y)
/// FROM (VALUES (0.0, -5.0), (3.0, 4.0), (-2.0, 10.0)) t(x, y);  -- -11/3
/// ```
#[duck_aggregate_function(
    auto_collect = true,
    description = "Population covariance of two DOUBLE columns, NULL when no row is fully non-NULL",
    comment = "A row with a NULL in either column is skipped entirely, keeping the two columns paired",
    example = "SELECT sr_population_covariance(x, y) FROM (VALUES (0.0, -5.0), (3.0, 4.0), (-2.0, 10.0)) t(x, y)"
)]
fn sr_population_covariance(x: Vec<f64>, y: Vec<f64>) -> DuckOptionResult<f64> {
    pairwise::<PopulationCovariance>(x, y)
}
